#!/usr/bin/env python3
"""
vault-runbook-refresh — refresh RUNBOOK.md auto-section.

Reads:
  - 02-Projects/<Name>/.wolf/buglog.json (if exists) — recent fixes
  - 02-Projects/<Name>/issues.md (if exists) — open known fires

Writes:
  - Replaces content between AUTO-START / AUTO-END markers in RUNBOOK.md
  - Manual section is never touched

Usage:
  python3 run.py --project <Name> [--vault <path>]

Idempotent. Safe to run repeatedly.
Stdlib only — no pip install.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from datetime import datetime
from pathlib import Path

DEFAULT_VAULT = os.path.expanduser("~/vault")
AUTO_START = "<!-- AUTO-START: vault-runbook-refresh -->"
AUTO_END = "<!-- AUTO-END: vault-runbook-refresh -->"
MAX_BUGS = 15
MAX_ISSUES = 10


def load_buglog(path: Path) -> list[dict]:
    if not path.exists():
        return []
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        if isinstance(data, list):
            return data
        if isinstance(data, dict) and "bugs" in data:
            return data["bugs"]
        return []
    except (json.JSONDecodeError, UnicodeDecodeError) as e:
        print(f"⚠️  Could not parse buglog: {e}", file=sys.stderr)
        return []


def parse_issues_md(path: Path) -> list[dict]:
    """Extract H2/H3 heading-anchored entries from issues.md."""
    if not path.exists():
        return []
    try:
        content = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return []

    issues = []
    # Match ## or ### heading + first non-empty line after as snippet
    pattern = re.compile(r"^(#{2,3})\s+(.+)$", re.MULTILINE)
    matches = list(pattern.finditer(content))
    for i, m in enumerate(matches):
        title = m.group(2).strip()
        start = m.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(content)
        body = content[start:end].strip()
        # First non-empty line as preview
        preview_lines = [ln.strip() for ln in body.splitlines() if ln.strip()]
        preview = preview_lines[0][:200] if preview_lines else ""
        issues.append({"title": title, "preview": preview})
    return issues


def render_auto_section(bugs: list[dict], issues: list[dict]) -> str:
    today = datetime.now().strftime("%Y-%m-%d")
    out = [AUTO_START, f"## 🤖 Auto-section (last refresh: {today})", ""]

    # Recent fixed incidents
    out.append("### Recent fixed incidents (from buglog)")
    if not bugs:
        out.append("_No incidents recorded yet._")
    else:
        recent = sorted(
            bugs, key=lambda b: b.get("last_seen", b.get("timestamp", "")), reverse=True
        )[:MAX_BUGS]
        for bug in recent:
            err = bug.get("error_message", "(no error_message)")
            cause = bug.get("root_cause", "(unknown)")
            fix = bug.get("fix", "(no fix recorded)")
            tags = bug.get("tags", [])
            tag_str = ", ".join(tags) if tags else ""
            seen = bug.get("last_seen", bug.get("timestamp", "—"))
            out.append(f"#### {err}")
            out.append(f"- **Root cause:** {cause}")
            out.append(f"- **Fix:** {fix}")
            if tag_str:
                out.append(f"- **Tags:** {tag_str}")
            out.append(f"- **Last seen:** {seen}")
            out.append("")
    out.append("")

    # Open known fires from issues.md
    out.append("### Open known fires (from issues.md)")
    if not issues:
        out.append("_No issues file or no entries parsed._")
    else:
        for issue in issues[:MAX_ISSUES]:
            preview = issue["preview"][:150]
            out.append(f"- **{issue['title']}** — {preview}")
    out.append("")

    out.append(f"_Generated by vault-runbook-refresh on {today}._")
    out.append(AUTO_END)
    return "\n".join(out)


def update_runbook(runbook_path: Path, new_block: str) -> tuple[bool, str]:
    """Replace AUTO-START..AUTO-END block. Dedupe if multiple. Append if missing."""
    if not runbook_path.exists():
        return False, f"RUNBOOK.md not found at {runbook_path}"

    content = runbook_path.read_text(encoding="utf-8")

    pattern = re.compile(
        re.escape(AUTO_START) + r".*?" + re.escape(AUTO_END),
        re.DOTALL,
    )
    matches = list(pattern.finditer(content))

    if matches:
        # Replace FIRST match, REMOVE all duplicates (idempotent across runs)
        parts: list[str] = []
        last_end = 0
        for i, m in enumerate(matches):
            parts.append(content[last_end:m.start()])
            if i == 0:
                parts.append(new_block)
            # else: skip (drop duplicate)
            last_end = m.end()
        parts.append(content[last_end:])
        new_content = "".join(parts)
        dup_n = len(matches) - 1
        action = (
            f"replaced existing block, removed {dup_n} duplicate(s)"
            if dup_n
            else "replaced existing block"
        )
    else:
        # No markers — append at end with separator
        sep = "\n\n---\n\n" if not content.endswith("\n") else "\n---\n\n"
        new_content = content.rstrip() + sep + new_block + "\n"
        action = "appended new block (markers were absent)"

    runbook_path.write_text(new_content, encoding="utf-8")
    return True, action


def main() -> int:
    parser = argparse.ArgumentParser(description="Refresh RUNBOOK.md auto-section")
    parser.add_argument("--project", required=True, help="Project name under 02-Projects/")
    parser.add_argument(
        "--vault",
        default=os.environ.get("AUTOFLOW_VAULT", DEFAULT_VAULT),
        help="Vault root (default: $AUTOFLOW_VAULT or master)",
    )
    args = parser.parse_args()

    vault = Path(args.vault)
    project_dir = vault / "02-Projects" / args.project

    if not project_dir.is_dir():
        print(f"❌ Project not found: {project_dir}", file=sys.stderr)
        return 1

    runbook = project_dir / "RUNBOOK.md"
    if not runbook.exists():
        print(
            f"❌ {args.project} has no RUNBOOK.md (not migrated to AutoFlow Standard)",
            file=sys.stderr,
        )
        return 2

    buglog_path = project_dir / ".wolf" / "buglog.json"
    issues_path = project_dir / "issues.md"

    bugs = load_buglog(buglog_path)
    issues = parse_issues_md(issues_path)

    block = render_auto_section(bugs, issues)
    ok, msg = update_runbook(runbook, block)
    if not ok:
        print(f"❌ {msg}", file=sys.stderr)
        return 3

    print(
        f"✅ {args.project}/RUNBOOK.md — {msg} "
        f"({len(bugs)} bugs, {len(issues)} issues)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
